// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCf6T3CjpD0Fvm2mViW3IjOoEneHYdPRw',
    appId: '1:471812222577:web:56a05440341443a4f0f5d0',
    messagingSenderId: '471812222577',
    projectId: 'notapp-ed0e2',
    authDomain: 'notapp-ed0e2.firebaseapp.com',
    storageBucket: 'notapp-ed0e2.appspot.com',
    measurementId: 'G-BSBL34MBHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnUTQ7OOJurPND2kRsUONUvgAE6dlvzDk',
    appId: '1:471812222577:android:4a472915f8cf95e5f0f5d0',
    messagingSenderId: '471812222577',
    projectId: 'notapp-ed0e2',
    storageBucket: 'notapp-ed0e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrnfnCUJHkObD8BdD3xwCJAtLNR1i_n68',
    appId: '1:471812222577:ios:9809e22cd8e4ae03f0f5d0',
    messagingSenderId: '471812222577',
    projectId: 'notapp-ed0e2',
    storageBucket: 'notapp-ed0e2.appspot.com',
    iosClientId: '471812222577-d2qp0cbhimj733ah081eujs0dafiq0gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kharchaBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrnfnCUJHkObD8BdD3xwCJAtLNR1i_n68',
    appId: '1:471812222577:ios:9809e22cd8e4ae03f0f5d0',
    messagingSenderId: '471812222577',
    projectId: 'notapp-ed0e2',
    storageBucket: 'notapp-ed0e2.appspot.com',
    iosClientId: '471812222577-d2qp0cbhimj733ah081eujs0dafiq0gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kharchaBook',
  );
}
